[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ragcore"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  "pydantic",
  "httpx",
  "numpy",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["ragcore*"]
