[project]
name = "datawoven-api"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = ["fastapi","uvicorn[standard]","pydantic-settings","httpx","psycopg2-binary","pgvector","qdrant-client","boto3"]
